### ISSUE TITLE
the enchantment ID is this the same for Electroblobs wizardry.

### ISSUE THREAD

**Issue by Belmoreworld** [KAMKEEL/CustomNPC-Plus#102]
when ever I try to put another mod on it crashes my game and it says that there are duplicate items. I have checked my mods folder and found no doubles of the same mods. but the crash report says that custom NPC+ enchantment ID is the same as one from Electroblobs Wizardry mod for 1.7.10

https://pastebin.com/UBxKxPc5

* Minecraft: 1.7.10
* Forge: 10.12.4.1614-1.7.10
* CustomNPC+: 

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

electroblobs wizardry mod  version 1.1.6 for minecraft 1.7.10 is required.

**Comment by KAMKEEL** [comment]
You can change the enchant start ID in the configs. In `config/CustomNpcPlus/main.cfg`. 

```
# Start ID for enchants. IDs can only range from 0-256
I:"Enchant Start ID"=100
```
