### ISSUE TITLE
 Question about the compatibility of this version of the mod with the original mod

### ISSUE THREAD

**Issue by Oleha1** [KAMKEEL/CustomNPC-Plus#104]
Hello, I have a couple of questions:
1) can I put this modification on the server
2) if I replace the original mod with CustomNPC-Plus, will there be any conflicts?

**Comment by KAMKEEL** [comment]
1. Yes it works on servers! Both servers and clients need it.
2. No, it should transition smoothly from CustomNpcs 1.7.10. That was the goal
