### ISSUE TITLE
World Lines not showing

### ISSUE THREAD

**Issue by Pilzinsel64** [KAMKEEL/CustomNPC-Plus#108]
**Issue description:**
If I setup World Lines for a NPC then they will not show up (not in chat and also not in a bubble). I expect them to show up either randomly or ordered with some seconds delay if I stand in the near of the NPC.

- I tested this on Version 1.8 without any mods, a clean install and a fresh new world.
- I tested this on Version 1.9 Beta 3 with all my mods and on my prod world.

If you want some logs, feel free, I attached theme here. They are from the instance where only CustomNPC+ is isntalled (and Waila, if im right).

Do I anthing wrong or are they just not working at the moment? I remember long time ago they shown. But to be fair, this can be at least one year ago, maybe more.

Would be really glad for help or a fix. Thank you in advance! 

**If crashed, link to crash report (use a site such as pastebin):**
[2023-05-04-3.log.gz](https://github.com/KAMKEEL/CustomNPC-Plus/files/13452446/2023-05-04-3.log.gz)
[CustomNPCs-1.log](https://github.com/KAMKEEL/CustomNPC-Plus/files/13452447/CustomNPCs-1.log)
[fml-client-3.log](https://github.com/KAMKEEL/CustomNPC-Plus/files/13452448/fml-client-3.log)

**Versions:**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+: 1.6-beta (up to currently 1.9 Beta 3)

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.** Yes, it can be reproduce with just CusotmNPC+.

**Comment by Pilzinsel64** [comment]
I tested a bit around and it seems that the bug has been introduced with 1.6-beta. So one of the over 250 commits might contain the reason... :/

**Comment by Pilzinsel64** [comment]
A world I used to reproduce the issue: [Neue Welt.zip](https://github.com/KAMKEEL/CustomNPC-Plus/files/13467005/Neue.Welt.zip)

**Comment by KAMKEEL** [comment]
@Pilzinsel64 It may have been resolved in this commit
https://github.com/KAMKEEL/CustomNPC-Plus/commit/90b34127c395c16793efdbfeb3011c06d72ab6a8

**Comment by KAMKEEL** [comment]
Reopen if still occuring
