### ISSUE TITLE
Ticking entity crashed

### ISSUE THREAD

**Issue by haha44444** [KAMKEEL/CustomNPC-Plus#115]
**Issue description:**
Crash when using Custom Npcs, then I tried using CustomNPC+, still the same.
**If crashed, link to crash report (use a site such as pastebin):**
https://api.mclo.gs/1/raw/YeKrmCd
**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* CustomNPC+: 1.8.6

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

**Comment by KAMKEEL** [comment]
@haha44444 Seems to be crashing somewhere within MC code. The function that's crashing is just a super call to the EntityLivingBase class. Which means... The mob itself may be corrupt by something else.

**Comment by KAMKEEL** [comment]
Marking as resolved @haha44444 reopen if issue persists
