### ISSUE TITLE
Custom NPC+ console commands not working in the quest section, in advanced, edit console command

### ISSUE THREAD

**Issue by levross23** [KAMKEEL/CustomNPC-Plus#122]
So ive recently opened my own forge server, running the Dragon Block C mods as ive wanted to create my own world. However ive run into an issue that only appears to be apparent on my online server, i.e ive tried in single player and it works fine. So when i create an NPC and create a quest attached to him, i want to edit the console command for when the quest is completed to give TP (Training points which is apart of the dragon block c mod). Using the command "/jrmctp 500 @dp" is suppost to give the character i have made 500 tp after i complete the quest, however it does not on my server. Only in single player mode does this work.

This command does work when i input the command into the Console of the server or in minecraft itself, just not when i ad it to the advanced section in quests, then in the console command. Has anyone ran into this issue also?

**Versions:**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+: 

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

**Comment by KAMKEEL** [comment]
@levross23 What version of CNPC+ are you on?

**Comment by levross23** [comment]
I'll have a check when I'm at my computer, do you recommend trying other release versions for 1.7.10?

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by levross23** [comment]
So im using Custom NPC Plus 1.21 at the moment

**Comment by levross23** [comment]
I have currently tried most of the other versions of the mod for 1.7.10 and they too arent working

**Comment by levross23** [comment]
I figured it out hahaha i didnt have command blocks enabled
