### ISSUE TITLE
CNPC+ API for modding

### ISSUE THREAD

**Issue by Veritaris** [KAMKEEL/CustomNPC-Plus#14]
**Issue description:**

Hi. This is great that u dudes decided to improve original modification. But I have a question - are you going to add any API so other mods would be able to communicate with CNPC, subscribe to it's own events, etc.?  I suppose this could be a great help to other modmakers 
I see that original author also made [API](https://github.com/Noppes/CustomNPCsAPI) for this (sadly, only for minecraft 1.8+ versions). 

**Versions:**
* Minecraft: 1.7.10
* Forge: 1.7.10-10.13.4.1614
* CustomNPC+: *

**Comment by KAMKEEL** [comment]
I see. I wasn't too aware of this but, I'll take a look!

**Comment by Veritaris** [comment]
Okay, thanks for your reply

**Comment by KAMKEEL** [comment]
As for looking into this, I most likely will not be persuing an API Extention as 1.7.10 is technically a dying breed for modding. I just don't see a point in allocating time for this.

**Comment by KAMKEEL** [comment]
@Veritaris After further consideration, we have decided to implement a full CNPC+ API!  https://github.com/KAMKEEL/CustomNPC-Plus-API/tree/main

**Comment by Veritaris** [comment]
Hi!
Yes, I saw commits in Discord and it's happy to see it is finally ready 
Thanks a lot for this great job!
