### ISSUE TITLE
Disabling items or blocks causes a crash.

### ISSUE THREAD

**Issue by MagmaBro123** [KAMKEEL/CustomNPC-Plus#27]
**Issue description:**
See title.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/rDLwYvKH

**Versions:**
Crash reports usually come with a modlist in them. Pastebin link has what you need.

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
Yes. CustomNPC and this fork don't need other mods. Again, see the Pastebin for the modlist.

**Comment by MagmaBro123** [comment]
See the Et discord

**Comment by MagmaBro123** [comment]
Issue Solved on Discord

**Comment by KAMKEEL** [comment]
Version 1.5-beta fixes this problem 👍🏾
