### ISSUE TITLE
Custom NPC aggro range not working as it should

### ISSUE THREAD

**Issue by Phan7om0120** [KAMKEEL/CustomNPC-Plus#34]
I don't know if its a bug or not but when I setting up an NPC to use a range attack and setting the range attack at least 30 blocks and visibility to 40 when they are seeing the target, they are spinning around, go little bit forward and back and dont attack the target, but when the target is really close to them, then they are decide to attack, i have checked everything, vision, range attack everything and its correct

**Comment by KAMKEEL** [comment]
You need to manually increase the change of the NPCs AggroRange for the server in the config. The default is 32 for memory and lag reasons. Technically, the config is a hard cap to the detection range.

**Comment by Phan7om0120** [comment]
But I already change aggro range from 32 to 96 in the config file and still doesn't work, NPC cant reach the target when its further than 8 blocks, in the close range he attacks normally but further the target is the NPC is disoriented and cant reach him

**Comment by KAMKEEL** [comment]
Would you mind sending me a copy of your clone data file? I can take a look and debug this when I get the time.

**Comment by Phan7om0120** [comment]
[Range Test 1.zip](https://github.com/KAMKEEL/CustomNPC-Plus/files/8060018/Range.Test.1.zip)

**Comment by Phan7om0120** [comment]
Yes I have found the solution for it, the sprint mode was messing with NPC when it was turned on, when its turned off everything goes back to normal, NPC is attacking at long range now
