### ISSUE TITLE
Linked npc lag

### ISSUE THREAD

**Issue by WhiteBless** [KAMKEEL/CustomNPC-Plus#35]
**Issue description:**
We found a bug that causes overall lag when operating linked npc to npcwand or Mobcopywand, so we report this.
**If crashed, link to crash report (use a site such as pastebin):**
https://youtu.be/t0FmnFTPBuk
**Versions:**
* Minecraft: 1.7.10
* Forge: 1.7.10-Forge10.13.4.1614-1.7.10
* CustomNPC+: 1.5.1 beta

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**

**Comment by KAMKEEL** [comment]
Either the server cannot handle the change efficiently or there is an error with the Linked Mob. Check your Client and Server logs to see if any details come up. Truth be told, I believe it is solely a performance issue. So unless- You're able to recreate this on a smaller scale then I won't be able to reproduce this.
