### ISSUE TITLE
Setting FontType has no effect

### ISSUE THREAD

**Issue by LSK-LW** [KAMKEEL/CustomNPC-Plus#52]
**Issue description:**
Setting FontType in config file has no effect
**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* CustomNPC+: 1.5.4

**Comment by KAMKEEL** [comment]
Did this work in previous versions?

**Comment by KAMKEEL** [comment]
No update, reopen if still occuring
