### ISSUE TITLE
FakePlayer Error

### ISSUE THREAD

**Issue by Goodbird-git** [KAMKEEL/CustomNPC-Plus#60]
**Issue description:**
There is an error with some event invokers in noppes.npcs.ScriptPlayerEventHandler, for example with method public void invoke(EntityStruckByLightningEvent event).
When  a sound is played for FakePlayer entity, the class cast exception occurs.
I've found this bug when tried to open a loot bag (LootBags-1.7.10-2.0.17 mod) with an Animation Tablet (ThaumicTinkerer-2.5-1.7.10-538)
The reason why it happens is that event.entity instanceof EntityPlayer does not grant you that event.entity will be instance of EntityPlayeMP (only then there will be no class cast exception here (IPlayer) NpcAPI.Instance().getIEntity(event.entity))
**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/tnXAQjE0
**Versions:**
* Minecraft: 1.7.10
* Forge: forge-1.7.10-10.13.4.1614-1.7.10
* CustomNPC+: last version
* ThaumicTinkerer-2.5-1.7.10-538
The bug can be reproduced with mods, using fake players, for example Thaumic tinkerer
Required mods for thaumic tinkerer are: Baubles, Thaumcraft, ThaumicTinkerer, LootBags

**Comment by KAMKEEL** [comment]
Can you test on the latest version to see if this bug still occurs? I think we may have a fix for this
