### ISSUE TITLE
CNPCs + 3D Model Weapons Render Issue (TechGuns, Matter Overdrive and etc.) 

### ISSUE THREAD

**Issue by TroubleDarkness** [KAMKEEL/CustomNPC-Plus#61]
**Issue description:**

Hi. NPCs just can't figure out how to hold any 3D Model guns and weapons from other mods. This problem has been haunting the mod since its earliest versions, unfortunately, it has not been fixed.
Of course, mod authors just slamdunk'd the support for mods on 1.12.2- Minecraft versions, like a Michael Jordan in basketball.

**Versions:**
* Minecraft: 1.7.10
* Forge: 1.7.10-10.13.4.1614
* CustomNPC+: *literally any version*

**To reproduce this issue you need:**

- Matter Overdrive

![2022-07-29_19 25 30](https://user-images.githubusercontent.com/33435797/181805633-c09e2ce1-f277-4ba3-a7b9-b3afd7f68dc8.png)

- TechGuns

![2022-07-29_19 25 59](https://user-images.githubusercontent.com/33435797/181805651-3c457f03-71cb-43c6-b066-cec85d7ec710.png)

Poor 9mm pistol guy.

**Comment by KAMKEEL** [comment]
Did this work in CNPC?

**Comment by TroubleDarkness** [comment]
Nope. It never worked.

**Comment by KAMKEEL** [comment]
@TroubleDarkness I believe I fixed the issue. Sadly, the orientation of _some_ 3D Items, like **Tech Guns** does not look properly yet (looks better), due to the fact they're designed to move orientation with the player arms.
