### ISSUE TITLE
CNPCs Knockback Resistance Issue + Sprint Attack and Item Knockback Enchantment

### ISSUE THREAD

**Issue by TroubleDarkness** [KAMKEEL/CustomNPC-Plus#62]
Issue description:

Hi. There is knockback resistance attribute on NPC's stats screen, that just not working for attacks while sprinting. So, npc's gets knocked back even in you managed to change this value on npc's json file. The problem also happens, when your item has knockback enchantment.

Versions:

Minecraft: 1.7.10
Forge: 1.7.10-10.13.4.1614
CustomNPC+: literally any version
To reproduce this issue you need CNPC+

Video demonstation:

https://youtu.be/9VHcuD3sKOg

**Comment by KAMKEEL** [comment]
Will be fixed in `1.6`
Reopen ticket if it's not
