### ISSUE TITLE
Dupe Immersive Engineering

### ISSUE THREAD

**Issue by Serega007RU** [KAMKEEL/CustomNPC-Plus#64]
**Issue description:** Dupe blast furnace and coke oven (possibly other multiblock structures), the video shows how to dupe.
Without CustomNPC Plus, this dupe does not work, so the problem is most likely in CustomNPC Plus

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:** Immersive Engineering v0.7.7
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* CustomNPC+: 1.6.1

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.** Immersive Engineering

https://www.youtube.com/watch?v=dB-MPtl73XE

**Comment by KAMKEEL** [comment]
Seems to be a 1.6 issue- Doesn't happen in 1.5.4. We will look into it. Thanks for reporting!

**Comment by KAMKEEL** [comment]
Confirmed caused by CustomNPC+. Investigating. Should be patched in 1.6.2
