### ISSUE TITLE
NPC's keep crashing 

### ISSUE THREAD

**Issue by Toastlord15** [KAMKEEL/CustomNPC-Plus#67]
So me and some friends have a server and whenever an npc drops an item or is killed it will crash our games I don't know if this is a common issue but it keeps happening to us and we have no idea why and when we updated to a newer version of the mod more issues showed up where the npcs whenever they would just fire something it would crash the game

**Comment by KAMKEEL** [comment]
Crash report? Which version of CNPC+? We need more details

**Comment by KAMKEEL** [comment]
Closing due to lack of information
