### ISSUE TITLE
CustomNPC Plus conflicts with Tinkers' Construct tabs

### ISSUE THREAD

**Issue by Omgise** [KAMKEEL/CustomNPC-Plus#68]
**Issue description:**
CustomNPC Plus conflicts with Tinkers' Construct tabs. You only need to switch back and forth to repeat this error.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* CustomNPC+: 
![image](https://user-images.githubusercontent.com/106000018/194000181-714f5a78-ff97-49b9-8362-ddd6967176b7.png)
**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
Tinkers' Construct

**Comment by KAMKEEL** [comment]
Can you test and see if this was created on our end? Use regular CustomNPCs 1.7.10 to test it

**Comment by eahraehoff** [comment]
Hi! I found this bug
Look at noppes.npcs.client.gui.player.GuiQuestLog
![image](https://user-images.githubusercontent.com/88247763/205459402-b6ea5802-5700-4653-8b0f-e6629669bcb5.png)

U want to change button ids. Tab Buttons with tinker has id 1-5

**Comment by KAMKEEL** [comment]
> Hi! I found this bug Look at noppes.npcs.client.gui.player.GuiQuestLog ![image](https://user-images.githubusercontent.com/88247763/205463895-e0fb983d-6187-4d26-bfaf-d84d76c5cb45.png)
> 
> U want to change button ids. Tab Buttons with tinker has id 1-5

@eahraehoff This is the GuiQuestLog it has nothing to do with Tinkers Tabs, but we'll look into this issue :)

**Comment by KAMKEEL** [comment]
@Omgise @eahraehoff 

Managed to finally catch the issue! Was a bit of weird one. CNPC+ v 1.9 will come out this month and will have the fix!
