### ISSUE TITLE
Mobs Won't Spawn

### ISSUE THREAD

**Issue by RubyRoseRed** [KAMKEEL/CustomNPC-Plus#77]
There seems to be an issue with mob spawning. I've tried messing with it and nothing makes it work, but before I switched to Custom NPC Plus I had several mobs that would spawn in various biomes, and now they've stopped spawning altogether. I've tried redoing it and it doesn't seem to work under any setting unless there's something I'm missing? I've also noticed some NPC's won't even spawn when using the mob-cloner wand, and give this error code:
![image](https://user-images.githubusercontent.com/42295054/227147628-f7baa609-9c6b-4e15-aa68-743bc263da11.png)

though I did try to set a spawn for an NPC that didn't give that error when I tried to manually spawn it as well, and that wouldn't naturally spawn, either.

* Minecraft: 1.7.10
* Forge: 10.13.4.1614.1.7.10
* CustomNPC+: CustomNPC-Plus-1.7

**Comment by KAMKEEL** [comment]
There is an issue with some information in the NPCs JSON File. Check the line number of the clone its given. Perhaps a corrupt item. It's attempt to convert the item within the NPC to a `NUM` but the value is actually a `LONG`.

**Comment by RubyRoseRed** [comment]
I could try to check that out next time I'm on my PC, however I tested this with several different mobs I tried to make spawn, and several didn't give me the error that I posted a screenshot of, they simply wouldn't spawn, ever. I reverted to the original customNPCs (losing all the great features the plus version has though, sadge) and the mobs would spawn perfectly fine for me again. Have you tested it, does it work for you when you try it?

**Comment by KAMKEEL** [comment]
I'm going to  need more logs for this. I think it is an issue with the NPC you're using.

**Comment by RubyRoseRed** [comment]
It happens to me with all the NPC's I've tried to test so far, new and old. Is the mob spawning working fine for you? How do I get you more logs to check on this?

**Comment by RubyRoseRed** [comment]
I'm not sure if that's it. I just went and removed that conveyer line from the NPC and now I can spawn it with a mob-spawner wand without the error just fine, and I've gone and made sure I can spawn in every NPC I have saved with the mob-spawner wand, however nothing spawns from the "natural spawns" even still

**Comment by RubyRoseRed** [comment]
![image](https://github.com/KAMKEEL/CustomNPC-Plus/assets/42295054/01c0bdd2-65a6-44d5-85b0-dd4eecf8ae65)
These are my mods and it's still not working

another update: I just had my friend test it with a FRESH new world and ONLY the custom NPCs+ 1.8 mod and natural spawns still isn't working?

**Comment by Marnex-0** [comment]
I'm testing CustomNpcs+ version 1.8, on both a thermos server and on a singeplayer session, Natural NPC Spawning does not seem to work, this was tested both with and without other mods, in both cases I have:

- Put all the biomes in the spawning biomes list
- Made sure all the dimensions are in the Spawning Dimensions list
- Set all the spawning options to Yes and made sure to set min and max height to 0 and 250 respectively
- Created and a new npc on each session and tried with a client saved one

Tested NPC's JSON files:
https://pastebin.com/EcjyixKx
https://pastebin.com/88PKCWm0

**Comment by KAMKEEL** [comment]
It's fixed in `1.8.1` thanks for the reports! We found what was causing it!
