### ISSUE TITLE
Crash with Fossils and Archeology/Aether/Custom Main Menu

### ISSUE THREAD

**Issue by Bryce-Knight** [KAMKEEL/CustomNPC-Plus#78]
**Issue description: If your modpack has any of the 3 mods listed in the title or has all 3 like mine the mods will NOT launch and the the pack will crash**

**If crashed, link to crash report (use a site such as pastebin): https://pastebin.com/21UCncpN**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.1614
* CustomNPC+: CustomNPC-Plus-1.7-nomixin

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
aether-1.7.10-1.6
Fossils-and-Archeology-Revival-Mod-1.7.10
CustomMainMenu-MC1.7.10-1.9.2

**Comment by KAMKEEL** [comment]
No response
