### ISSUE TITLE
desynced armor on animation

### ISSUE THREAD

**Issue by 20Whey** [KAMKEEL/CustomNPC-Plus#82]
**Issue description:**
when rotating or changing pivot positions by significant margins, armour model seems to animate at different speeds to the main body.

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1558
* CustomNPC+: 1.8

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
can be reproduced both offline and online with CNPC+
https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/27d13cd9-07e2-4da2-b313-b47815348e99

**Comment by KAMKEEL** [comment]
Thanks for the report! We made no changes in `1.8.1` regarding this so we'll look to patch this soon!

**Comment by KAMKEEL** [comment]
Fixed!
