### ISSUE TITLE
Event Script related server crash

### ISSUE THREAD

**Issue by Douggernort** [KAMKEEL/CustomNPC-Plus#84]
**Issue description:**
I was trying event scripting for the first time, nothing was happening in the melee attack event - I placed a comment inside and then immediately crashed. in singleplayer the melee attack event doesn't seem to be working.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.1.1558
* CustomNPC+: 1.8.1
      the important bit -     
      |
     V
[crash-2023-05-11_01.08.12-server.txt](https://github.com/KAMKEEL/CustomNPC-Plus/files/11447211/crash-2023-05-11_01.08.12-server.txt)

**Comment by Douggernort** [comment]
function target(event){
event.npc.setTempData("count", 0);
var targ = event.getTarget();
var targE = event.getTarget().getMCEntity();
event.npc.setTempData("targ", targ);
}

function targetLost(event){
event.npc.setTempData("targ", null);
}

function meleeAttack(event){
var count = event.npc.getTempData("count");
if (count < 3){
    count++;
} else {
    event.npc.getTimers().forceStart(0, 1, false);
}}


function timer(event){

    switch(event.id){
        case 0:
var anim = event.API.getAnimations().get("bShieldBash");
var animData = event.npc.getAnimationData();
animData.setEnabled(true);
animData.setAnimation(anim);
animData.updateClient();
event.npc.say("take this!");
/*
p.addPotionEffect(15, 1, 0, false);
p.addPotionEffect(9, 5, 0, false);
*/
break;
    
case 1:
npc.getMCEntity().func_70652_k(npc.getTempData("targ").getMCEntity());
break;
}


}

**Comment by KAMKEEL** [comment]
Fixed in SHA 8a4c9f6f6b47262acf3c3c47b04cf48db7379776
Will be available in the `1.8.2` update when released. Thanks for being patient.
