### ISSUE TITLE
Crash upon server join

### ISSUE THREAD

**Issue by Douggernort** [KAMKEEL/CustomNPC-Plus#89]
**Issue description:**
crash upon join
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1558
* CustomNPC+: 1.9 experim

important bit :

[B#773]  [06:34:03] [Client thread/ERROR]: 1: ASM: noppes.npcs.client.PacketHandlerClient@3d6b483d onPacketData(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientCustomPacketEvent;)V
[B#773]  [06:34:03] [Client thread/ERROR]: NetworkEventFiringHandler exception
[B#773]  java.lang.NullPointerException
[B#773]  	at noppes.npcs.controllers.data.PlayerQuestData.loadNBTData(PlayerQuestData.java:60) ~[PlayerQuestData.class:?]
[B#773]  	at noppes.npcs.controllers.data.PlayerData.setNBT(PlayerData.java:85) ~[PlayerData.class:?]
[B#773]  	at noppes.npcs.client.PacketHandlerClient.client(PacketHandlerClient.java:114) ~[PacketHandlerClient.class:?]
[B#773]  	at noppes.npcs.client.PacketHandlerClient.onPacketData(PacketHandlerClient.java:53) ~[PacketHandlerClient.class:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler_279_PacketHandlerClient_onPacketData_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
[B#773]  	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
[B#773]  	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
[B#773]  	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
[B#773]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#773]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#773]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#773]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#773]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#773]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#773]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#773]  	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#773]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
[B#773]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
[B#773]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
[B#773]  	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
[B#773]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#773]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#773]  [06:34:03] [Client thread/ERROR]: There was a critical exception handling a packet on channel CustomNPCs
[B#773]  java.lang.NullPointerException
[B#773]  	at noppes.npcs.controllers.data.PlayerQuestData.loadNBTData(PlayerQuestData.java:60) ~[PlayerQuestData.class:?]
[B#773]  	at noppes.npcs.controllers.data.PlayerData.setNBT(PlayerData.java:85) ~[PlayerData.class:?]
[B#773]  	at noppes.npcs.client.PacketHandlerClient.client(PacketHandlerClient.java:114) ~[PacketHandlerClient.class:?]
[B#773]  	at noppes.npcs.client.PacketHandlerClient.onPacketData(PacketHandlerClient.java:53) ~[PacketHandlerClient.class:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler_279_PacketHandlerClient_onPacketData_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[B#773]  	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
[B#773]  	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
[B#773]  	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
[B#773]  	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
[B#773]  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[B#773]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#773]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#773]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[B#773]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[B#773]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#773]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#773]  	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
[B#773]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#773]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
[B#773]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
[B#773]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
[B#773]  	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
[B#773]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#773]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[techniclauncher_2023-05-17.log](https://github.com/KAMKEEL/CustomNPC-Plus/files/11494555/techniclauncher_2023-05-17.log)

**Comment by KAMKEEL** [comment]
1.9 Sync will likely be discontinued due to a lot of unforeseen bugs.

**Comment by Douggernort** [comment]
ah, I understand - thank you for the update!
