### ISSUE TITLE
[bug] offset with event.player.getLookingAtBlock();

### ISSUE THREAD

**Issue by Douggernort** [KAMKEEL/CustomNPC-Plus#90]
**Issue description:**
There is a noticable offset from where raycast should be fired and where it hits.
**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1558
* CustomNPC+: 1.8.3

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
![Screenshot 2023-05-21 122421](https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/9b396946-94ef-4aff-8b16-9633306531d0)
![Screenshot 2023-05-21 123112](https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/2edc57b0-ec0f-486a-b7d8-d6a9861cdb9e)

**Comment by c0508383** [comment]
Ray casting blocks and positions has now been improved overall. Because we're not running things on the client-side, it won't be 100% accurate, but it's a massive improvement over an entire block offset! Thank you for the report.

**Comment by c0508383** [comment]
(To be clear it's off by maybe a pixel or two)

**Comment by Douggernort** [comment]
Thank you for the fix!
