### ISSUE TITLE
[bug] itemslots not using the id that's set

### ISSUE THREAD

**Issue by Douggernort** [KAMKEEL/CustomNPC-Plus#91]
**Issue description:**
When an itemslot is created via: event.gui.addItemSlot(int id, int x, int y);
the id is completely detached from the itemSlot events, so it has no real use currently.
**Versions:**
* Minecraft: 1.7.10
* Forge: the sameold sameold
* CustomNPC+: 1.8.3
![image](https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/fff07183-63cc-4c7e-9515-a0ee9bfccd16)
https://media.discordapp.net/attachments/1003994806457999461/1110557599360884857/image.png?width=401&height=105

**Comment by c0508383** [comment]
Fixed! The old functionality of event.slotId has simply stayed around. If you want to get the component's ID in the GUI, you get it through event.slot.getID() instead.

**Comment by Douggernort** [comment]
Thank you for the fix!
