### ISSUE TITLE
[bug] UI creation of itemslot and subequent updated UI causing crash when new itemslot is clicked

### ISSUE THREAD

**Issue by Douggernort** [KAMKEEL/CustomNPC-Plus#93]
**If crashed, link to crash report (use a site such as pastebin):**
paste.ee containing the player script required to reproduce.
https://paste.ee/p/5ujXl
**Versions:**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+: 1.8.4 beta
client crash in sp and client kicked from server in mp - I sent the same script to Hanad or Zaxar#2257 on discord to try and he had similar results.

24.05 15:40:25 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 74, Size: 37
24.05 15:40:25 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_362]
24.05 15:40:25 [Server] INFO at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_362]
24.05 15:40:25 [Server] INFO at noppes.npcs.containers.ContainerCustomGui.func_75144_a(ContainerCustomGui.java:111) ~[ContainerCustomGui.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2086) ~[nh.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
24.05 15:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
24.05 15:40:25 [Server] INFO at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]

**Comment by c0508383** [comment]
All fixed, thanks for the report!

**Comment by Douggernort** [comment]
Thank you for the fix!
