### ISSUE TITLE
Crashing when summing npc

### ISSUE THREAD

**Issue by RickyTheMoleRat** [KAMKEEL/CustomNPC-Plus#95]
So I added the mod to the mod folder and used it with flans mod for npc, after opening a world and trying to place a npc it crashes and says "The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchFieldError: NpcNavRange" I tried removing other mods but it still crashes

here is the crash report: ---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 
Description: Exception in server tick loop

java.lang.NoSuchFieldError: NpcNavRange
	at noppes.npcs.entity.EntityNPCInterface.func_110147_ax(EntityNPCInterface.java:288)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:120)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:68)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at noppes.npcs.entity.EntityNPCInterface.<init>(EntityNPCInterface.java:243)
	at noppes.npcs.entity.EntityNPCFlying.<init>(EntityNPCFlying.java:13)
	at noppes.npcs.entity.EntityCustomNpc.<init>(EntityCustomNpc.java:27)
	at noppes.npcs.items.ItemNpcWand.func_77648_a(ItemNpcWand.java:46)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 135271016 bytes (129 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] (1.7.10bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (1.7.10DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] (1.7.10Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	customnpcs{1.8.5} [CustomNPC+] (CustomNPC-Plus-1.8.5.jar) 
	UCHIJAAAA	flansmod{1.56} [Flan's Mod Ultimate] (Flan's+Mod+Ultimate+Stability+Edition-1.56.jar) 
	UCHIJAAAA	npcflancompatibility{1.0} [CustomNPCs Flan Compatibility Mod] ([1.7.10]-Flan's-Mod-NPC-Vehicles-4.0.jar) 
	UCHIJAAAA	wolffsmod{4.0} [Flan's Mod NPC Vehicles] ([1.7.10]-Flan's-Mod-NPC-Vehicles-4.0.jar) 
	UCHIJAAAA	mod.ymt.air.HariboteAirCraft{172v2 hiten} [HariboteAirCraft] (aircraft-mod-1.7.2.zip) 
	UCHIJAAAA	AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-1.7.10-1.0.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (architecturecraft-1.7.2-mc1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.81.7.10.jar) 
	UCHIJAAAA	mw{0.4.2.4} [Modern Warfare Contagion] (mw_2.0-0.4.2.4+(Halloween+Update)_mc1.7.10.jar) 
	UCHIJAAAA	roadstuff{0.4.0} [Road Stuff] (RoadStuff_mc1.7.10_0.4.0.jar) 
	UCHIJAAAA	signpic{2.8.0} [SignPicture] (SignPicture_1.7.10_2.8.0_universal.jar) 
	UCHIJAAAA	staircraftmod{1.7} [Staircraft] (staircraftmod-1.7-1.7.10-forge.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila_1.5.10_1.7.10.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (wailaharvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Flan's Mod Content Packs: 
flans_simple_parts_pack_1.7.10.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/flans_simple_parts_pack_1.7.10.jar)
Monolith Pack Version 3 Ausf. C (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/Monolith Pack Version 3 Ausf. C)
Warfare44ContentPackForMTS-Version_1.0.0.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/Warfare44ContentPackForMTS-Version_1.0.0.jar)
Minecraft SMP Parts Package 4.0-Content Pack-1.7.10-4.10.0 (2).jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/Minecraft SMP Parts Package 4.0-Content Pack-1.7.10-4.10.0 (2).jar)
WW2-Content Pack-1.7.10-4.10.0(1).jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/WW2-Content Pack-1.7.10-4.10.0(1).jar)
warfare-44-content-pack-1_7_10.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/warfare-44-content-pack-1_7_10.jar)
ManusWW2Package-Content Pack V4.0-1.7.10-4.10.0.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/ManusWW2Package-Content Pack V4.0-1.7.10-4.10.0.jar)
italian-ww2-pack-3d-v1.3.zip (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/italian-ww2-pack-3d-v1.3.zip)
British-Military-Pack-V1.12.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/British-Military-Pack-V1.12.jar)
[1.7.10]+Wolff's+Germany+WW2+Pack-2.3.jar (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/[1.7.10]+Wolff's+Germany+WW2+Pack-2.3.jar)
dr_prof_luigis_pack_1_7_10.zip (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/dr_prof_luigis_pack_1_7_10.zip)
akaku-vehicle-package-3.1-for-1.7.10.zip (filepath: /Users/noorullah/Library/Application Support/minecraft/Flan/akaku-vehicle-package-3.1-for-1.7.10.zip)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['RickyTheMoleRat'/38, l='New World', x=1278.52, y=4.00, z=142.58]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Versions:**
* Minecraft: 1.7.10
* Forge: 
* CustomNPC+:

**Comment by KAMKEEL** [comment]
Caused by `wolffsmod{4.0} [Flan's Mod NPC Vehicles]`. Does not work with CNPC+ 1.8. Only works with 1.7 and lower. Please visit their discord about this issue. https://discord.com/invite/BrZF5bn3ZY
