### ISSUE TITLE
Itemslots created via script don't have an id - also a visual itemslot /*duplication*/ bug when creating new itemslots

### ISSUE THREAD

**Issue by 20Whey** [KAMKEEL/CustomNPC-Plus#97]
**Issue description:**
creating itemslots via script seems to duplicate them, duplicated itemslots and normal itemslots created via script aren't acessible via  id.
can be produced in single player and multiplayer.

**Versions:**
* Minecraft: 1.7.10
* Forge: 10.13.4.1558
* CustomNPC+: 1.8.5

**Can it be reproduced with *just* CustomNPC+? If not, list the other mods *required* to reproduce the issue.**
I'm fairly certain this is just cnpc+
https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/d2f74da4-20bf-4acd-b131-1a46c8100dd3

https://github.com/KAMKEEL/CustomNPC-Plus/assets/31368984/3f82e052-332d-4423-9c33-6e0bae963f97
as shown in this video, they are still the correct amount of slots? so I'm confused by the way the ui updates

**Comment by Douggernort** [comment]
discovered the issue is gui.update(event.player);

**Comment by Douggernort** [comment]
it's a visual bug, not straight duplication
